### ISSUE TITLE
[Problem Executing the Project] (OS) One liner description of the issue.

### ISSUE THREAD

**Issue by mervenur3** [HaiderAbasi/ROS2-Path-Planning-and-Maze-Solving#11]
![Screenshot from 2023-11-09 10-24-30](https://github.com/HaiderAbasi/ROS2-Path-Planning-and-Maze-Solving/assets/45712541/bb31613a-90c4-4852-859d-8c81eab71050)
### Prerequisites

* [y ] Are you running the latest version (Repo)?
* [y ] Did you follow the How_to_Run_the_project guide in Section 1 (Lec 1 & 2)?
* [y] Did you check Issues on Github for related queries?
* [y ] Did you try restarting the PC and re-doing the steps in Section 1 (Lec 1 & 2)?
* [y ] Is the problem persistent?

### Description

I follow the video instructions and setup everything according to it. I could not run  maze_2_robot_camera.launch.py from beginning from lecture 1, part 4. Run Complete Project without docker.

### Steps to Reproduce

1. colcon build 
getting just this:  Starting >>> maze_bot
Finished <<< maze_bot [4.31s]           

Summary: 1 package finished [10.7s]

2. source install/setup.bash
3.ros2 launch maze_bot maze_2_robot_camera.launch.py

**Expected behavior:** 
I expect to get reaction as what happened in the video. After running 'ros2 launch maze_bot maze_2_robot_camera.launch.py', Gazebo should have opened. 

**Actual behavior:** 
I am getting this information/messages: 
[INFO] [launch]: All log files can be found below /home/merve/.ros/log/2023-11-09-02-03-08-924152-merve-Katana-GF76-11UC-22445
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 62, in get_launch_description_from_python_launch_file
    launch_file_module = load_python_launch_file_as_module(python_launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 37, in load_python_launch_file_as_module
    loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/merve/Masaüstü/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/install/maze_bot/share/maze_bot/launch/maze_2_robot_camera.launch.py", line 6, in <module>
    from scripts import GazeboRosPaths
ImportError: cannot import name 'GazeboRosPaths' from 'scripts' (/home/merve/.local/lib/python3.8/site-packages/scripts/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: cannot import name 'GazeboRosPaths' from 'scripts' (/home/merve/.local/lib/python3.8/site-packages/scripts/__init__.py)

**Screenshots**

![Screenshot from 2023-11-09 02-24-39](https://github.com/HaiderAbasi/ROS2-Path-Planning-and-Maze-Solving/assets/45712541/ac0c8447-2db1-4db5-b2b9-0f44543f43a8)

**Environment (please complete the following information):**
 - Ubuntu 20.04 LTS]
 - Python 3.8.10
 - OpenCV-Version 4.8.1

**Hardware**
-  Laptop
- Make-Model (If Any) [ MSI - GF76]
- GPU [e.g. Nvidia RTX 3050 Ti]

**Comment by noshluk2** [comment]
Kindly check if this command solves your problem 

`sudo apt install ros-foxy-gazebo-* `

**Comment by HaiderAbasi** [comment]
Closing this due to inactivity, 
Reopen if problem arise again.
